### ISSUE TITLE
Add info to SystemInformationToolbar

### ISSUE THREAD

**Issue by runepiper** [visuellverstehen/t3visuellverstehen#2]
We could also easily add information to the SystemInformationToolbar. E.g.:

![Bildschirmfoto 2020-10-08 um 15 08 15](https://user-images.githubusercontent.com/4521147/95463043-970eff00-0978-11eb-9a9f-cc649fdcce7f.png)

Opinions?

**Comment by malteriechmann** [comment]
Good to know. I kinda like the little bug.

I am not sure, if this is the right place for such information. This section is only for information about the system.

@runepiper @timonschoenfeld What is your opinion?

**Comment by runepiper** [comment]
I will close this for now.
